# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'jars/installer'

RSpec::Core::RakeTask.new(:spec)

require 'rubocop/rake_task'

RuboCop::RakeTask.new

namespace :jars do
  desc 'Download jar dependencies and generate a jar-linker file'
  task :install do
    Jars::Installer.vendor_jars!
  end
end

task default: %i[spec rubocop]
